import { GoalTemplate } from '@/types';

export const goalTemplates: GoalTemplate[] = [
  {
    id: 'startup-launch',
    name: 'Launch a Startup',
    category: 'career',
    description: 'Complete roadmap for launching your startup from idea to market',
    icon: '🚀',
    estimatedDuration: '6 months',
    difficulty: 'advanced',
    templateTasks: [
      {
        title: 'Validate Business Idea',
        description: 'Conduct market research and validate your business concept',
        estimatedDuration: '2 weeks',
        order: 1,
      },
      {
        title: 'Create Business Plan',
        description: 'Develop comprehensive business plan with financials',
        estimatedDuration: '2 weeks',
        order: 2,
      },
      {
        title: 'Build MVP',
        description: 'Develop minimum viable product',
        estimatedDuration: '2 months',
        order: 3,
      },
      {
        title: 'Get First Customers',
        description: 'Launch beta and acquire initial users',
        estimatedDuration: '1 month',
        order: 4,
      },
      {
        title: 'Secure Funding',
        description: 'Pitch to investors or bootstrap',
        estimatedDuration: '1 month',
        order: 5,
      },
    ],
  },
  {
    id: 'exam-preparation',
    name: 'Exam Preparation',
    category: 'education',
    description: 'Structured study plan for acing your exams',
    icon: '📚',
    estimatedDuration: '3 months',
    difficulty: 'intermediate',
    templateTasks: [
      {
        title: 'Create Study Schedule',
        description: 'Map out topics and create realistic timeline',
        estimatedDuration: '3 days',
        order: 1,
      },
      {
        title: 'Gather Study Materials',
        description: 'Collect textbooks, notes, and online resources',
        estimatedDuration: '1 week',
        order: 2,
      },
      {
        title: 'Study Core Concepts',
        description: 'Deep dive into fundamental topics',
        estimatedDuration: '6 weeks',
        order: 3,
      },
      {
        title: 'Practice Problems',
        description: 'Solve practice questions and past papers',
        estimatedDuration: '4 weeks',
        order: 4,
      },
      {
        title: 'Review and Mock Tests',
        description: 'Take full-length mock exams',
        estimatedDuration: '2 weeks',
        order: 5,
      },
    ],
  },
  {
    id: 'fitness-journey',
    name: 'Fitness Transformation',
    category: 'fitness',
    description: 'Get fit and healthy with a structured workout and nutrition plan',
    icon: '💪',
    estimatedDuration: '3 months',
    difficulty: 'beginner',
    templateTasks: [
      {
        title: 'Set Fitness Goals',
        description: 'Define specific, measurable fitness objectives',
        estimatedDuration: '1 week',
        order: 1,
      },
      {
        title: 'Create Workout Plan',
        description: 'Design weekly workout routine',
        estimatedDuration: '1 week',
        order: 2,
      },
      {
        title: 'Plan Nutrition',
        description: 'Develop healthy meal plan and track macros',
        estimatedDuration: '1 week',
        order: 3,
      },
      {
        title: 'Build Exercise Habit',
        description: 'Workout consistently 3-5 times per week',
        estimatedDuration: '8 weeks',
        order: 4,
      },
      {
        title: 'Track Progress',
        description: 'Monitor weight, measurements, and strength gains',
        estimatedDuration: 'Ongoing',
        order: 5,
      },
    ],
  },
  {
    id: 'umrah-preparation',
    name: 'Umrah Preparation',
    category: 'spiritual',
    description: 'Complete spiritual and logistical preparation for Umrah',
    icon: '🕌',
    estimatedDuration: '2 months',
    difficulty: 'beginner',
    templateTasks: [
      {
        title: 'Learn Umrah Rituals',
        description: 'Study the proper way to perform Umrah',
        estimatedDuration: '2 weeks',
        order: 1,
      },
      {
        title: 'Book Travel and Accommodation',
        description: 'Arrange flights, hotel, and visa',
        estimatedDuration: '1 week',
        order: 2,
      },
      {
        title: 'Spiritual Preparation',
        description: 'Increase worship and make dua lists',
        estimatedDuration: '3 weeks',
        order: 3,
      },
      {
        title: 'Physical Preparation',
        description: 'Get fit for walking and prepare health items',
        estimatedDuration: '2 weeks',
        order: 4,
      },
      {
        title: 'Final Preparations',
        description: 'Pack, review rituals, and prepare mentally',
        estimatedDuration: '1 week',
        order: 5,
      },
    ],
  },
  {
    id: 'creative-project',
    name: 'Complete Creative Project',
    category: 'creative',
    description: 'Finish that creative project you\'ve been putting off',
    icon: '🎨',
    estimatedDuration: '2 months',
    difficulty: 'intermediate',
    templateTasks: [
      {
        title: 'Define Project Scope',
        description: 'Clearly outline what you want to create',
        estimatedDuration: '3 days',
        order: 1,
      },
      {
        title: 'Research and Inspiration',
        description: 'Gather references and inspiration',
        estimatedDuration: '1 week',
        order: 2,
      },
      {
        title: 'Create Rough Draft',
        description: 'Make initial version without perfectionism',
        estimatedDuration: '3 weeks',
        order: 3,
      },
      {
        title: 'Refine and Iterate',
        description: 'Polish and improve your work',
        estimatedDuration: '3 weeks',
        order: 4,
      },
      {
        title: 'Finalize and Share',
        description: 'Complete final version and publish/share',
        estimatedDuration: '1 week',
        order: 5,
      },
    ],
  },
  {
    id: 'learn-language',
    name: 'Learn a New Language',
    category: 'education',
    description: 'Achieve conversational fluency in a new language',
    icon: '🗣️',
    estimatedDuration: '6 months',
    difficulty: 'intermediate',
    templateTasks: [
      {
        title: 'Master Basics',
        description: 'Learn alphabet, pronunciation, and basic grammar',
        estimatedDuration: '3 weeks',
        order: 1,
      },
      {
        title: 'Build Vocabulary',
        description: 'Learn 1000 most common words',
        estimatedDuration: '2 months',
        order: 2,
      },
      {
        title: 'Practice Speaking',
        description: 'Have conversations with native speakers',
        estimatedDuration: '2 months',
        order: 3,
      },
      {
        title: 'Consume Content',
        description: 'Watch shows, read books in target language',
        estimatedDuration: '1 month',
        order: 4,
      },
      {
        title: 'Achieve Fluency',
        description: 'Practice daily until conversationally fluent',
        estimatedDuration: '1 month',
        order: 5,
      },
    ],
  },
];

